#!/usr/bin/env python3
"""Nested-OOF conservative one-swap policies for strict native Graph candidates.

This is a development-only, full-information one-step contextual policy
experiment.  It consumes the already frozen strict-native provenance ledger,
the fully judged D8+Depth4+Graph4 pool, and the exact query-grouped splits used
by the preceding strict-SBERT selector experiment.

The experiment deliberately keeps the following boundaries explicit:

* ``mixed_lambdamart_depth`` is frozen before this experiment and is never
  re-selected from policy outcomes;
* outer-validation baseline sets are exact reproductions of the prior OOF
  selector, while outer-train baseline features are generated by inner OOF;
* action eligibility is utility-blind and every eligible replacement receives
  its full-information reward only after its feature vector is frozen;
* every model has an implicit NO-OP action with fixed score zero and a
  conservative threshold selected only from inner query-grouped OOF;
* repeated OOF rows are averaged within the same query before bootstrap;
* frozen test paths and external model calls are rejected.

The implementation is not PPO, GRPO, REINFORCE, a multi-step agent, or a
logged-bandit estimator.  The linear and MLP arms directly optimize the known
expected one-step reward table under a softmax policy.
"""
from __future__ import annotations

import argparse
import csv
import json
import math
import os
import statistics
import tempfile
from collections import Counter, defaultdict
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable

import numpy as np

# Keep the repository's macOS native-runtime import order: XGBoost before the
# canonical reranker module imports Torch.
import xgboost as _xgboost  # noqa: F401

try:
    import configuration as project_config
    from evaluation.fusion_strategy_ablation import (
        _utility as canonical_utility_at8,
    )
    from evaluation.judgment_completeness import (
        complete_utility_v2_rows,
    )
    from evaluation.statistics import bootstrap_ci
    from utility_scoring.learned_diffusion import reranker_validation as canonical
    from candidate_pool.analyze_strict_sbert_graph_oracle import (
        _read_jsonl,
        _reject_test,
        _sha256,
        _write_json,
        _write_jsonl,
    )
    from evidence_selection.run_strict_sbert_mixed_selector import (
        GRAPH,
        MixedDataset,
    )
except ModuleNotFoundError:
    import sys

    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
    import configuration as project_config
    from evaluation.fusion_strategy_ablation import (
        _utility as canonical_utility_at8,
    )
    from evaluation.judgment_completeness import (
        complete_utility_v2_rows,
    )
    from evaluation.statistics import bootstrap_ci
    from utility_scoring.learned_diffusion import reranker_validation as canonical
    from candidate_pool.analyze_strict_sbert_graph_oracle import (
        _read_jsonl,
        _reject_test,
        _sha256,
        _write_json,
        _write_jsonl,
    )
    from evidence_selection.run_strict_sbert_mixed_selector import (
        GRAPH,
        MixedDataset,
    )

from sklearn.linear_model import HuberRegressor, Ridge
from sklearn.preprocessing import StandardScaler

import torch
from torch import nn


MODEL_FEATURES = (
    "sbert_query_candidate_score",
    "sbert_query_candidate_relative",
    "ppr_no_recognition_score",
    "ppr_no_recognition_rank_norm",
    "ppr_fact_only_score",
    "ppr_fact_only_rank_norm",
    "route_both",
    "route_fact_only_only",
    "route_no_recognition_only",
    "route_rank_agreement",
    "route_score_agreement",
    "graph_exclusive",
    "dense_score_missing",
    "candidate_novelty_to_s0",
    "candidate_mean_similarity_to_s0",
    "candidate_tail_similarity",
    "candidate_centroid_distance",
    "s0_internal_mean_similarity",
    "predicted_utility_difference",
    "query_relevance_difference",
    "baseline_selector_score_difference",
    "novelty_difference",
    "candidate_replaced_similarity",
    "normalized_rank_difference",
    "s0_predicted_utility_std",
)

DIAGNOSTIC_FEATURES = (
    "candidate_max_similarity_to_s0",
    "s0_internal_max_similarity",
    "s0_predicted_utility_min",
    "s0_predicted_utility_mean",
    "s0_predicted_utility_max",
    "s0_tail_selector_score_gap",
    "candidate_pool_sbert_score_dispersion",
)

FORBIDDEN_INFERENCE_FEATURES = (
    "gold_utility",
    "gold_reward",
    "raw_reward",
    "oracle_opportunity",
    "oracle_action",
    "graph_seed_mass",
    "graph_seed_score_inputs",
    "pair_margin",
)

POOL_STRICT = "graph_strict_native_all"
POOL_FACT_ONLY = "graph_fact_only_supported"
POOL_DEPTH = "matched_depth_rescue"
POOL_NO_RECOGNITION_ONLY = "graph_no_recognition_only"
MODEL_FAMILIES = ("direct_delta", "linear_policy", "small_mlp_policy")
THRESHOLD_MODES = ("none", "nested")
VERDICTS = {
    "STRICT_NATIVE_GRAPH_HEADROOM_CONVERTED",
    "STRICT_NATIVE_GRAPH_SELECTIVE_SIGNAL_ONLY",
    "SECOND_STAGE_REPLACEMENT_EFFECT_NOT_GRAPH_SPECIFIC",
    "STRICT_NATIVE_GRAPH_NOT_CONVERTED_BY_CONSERVATIVE_ONE_STEP_POLICY",
}


def _resolve(root: Path, value: str | Path) -> Path:
    path = Path(value)
    return path if path.is_absolute() else root / path


def _mean_and_se(values: list[float]) -> tuple[float, float]:
    if not values:
        return 0.0, 0.0
    mean = statistics.fmean(values)
    if len(values) < 2:
        return mean, 0.0
    return mean, statistics.stdev(values) / math.sqrt(len(values))


def _minmax(values: Iterable[float]) -> list[float]:
    values = [float(value) for value in values]
    if not values:
        return []
    low, high = min(values), max(values)
    if high <= low:
        return [0.0 for _ in values]
    return [(value - low) / (high - low) for value in values]


def _cosine(left: np.ndarray, right: np.ndarray) -> float:
    return float(np.clip(np.dot(left, right), -1.0, 1.0))


def _utility_at8(
    ids: list[str],
    query_id: str,
    qrels: dict[tuple[str, str], dict],
) -> float:
    """Use the project's existing exact Utility@8 implementation."""
    value = canonical_utility_at8(ids, query_id, qrels)
    if value is None:
        raise ValueError(f"{query_id}: incomplete Utility@8 set {ids}")
    return float(value)


def _write_csv(path: Path, rows: list[dict]) -> None:
    if not rows:
        path.write_text("", encoding="utf-8")
        return
    fieldnames = sorted({key for row in rows for key in row})
    preferred = [
        "query_id",
        "arm",
        "pool",
        "action_space",
        "model_family",
        "threshold_mode",
    ]
    fieldnames = [
        *[key for key in preferred if key in fieldnames],
        *[key for key in fieldnames if key not in preferred],
    ]
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def _route_category(provenance: dict) -> str:
    routes = set(map(str, provenance.get("graph_pre_fallback_rank", {})))
    has_no = "no_recognition" in routes
    has_fact = "fact_only_no_recognition" in routes
    if has_no and has_fact:
        return "both_routes"
    if has_fact:
        return "fact_only_only"
    if has_no:
        return "no_recognition_only"
    return "no_native_graph_route"


def _rank_depth(
    dataset: MixedDataset,
    query_id: str,
    scores: np.ndarray,
    top_k: int,
) -> list[int]:
    indices = [
        index
        for index in dataset.by_query[query_id]
        if str(dataset.rows[index]["candidate_source"]) != GRAPH
    ]
    return sorted(
        indices,
        key=lambda index: (
            -float(scores[index]),
            str(dataset.rows[index]["comment_id"]),
        ),
    )[:top_k]


def _fit_baseline_scores(
    dataset: MixedDataset,
    train_qids: list[str],
    settings: dict,
    *,
    seed: int,
    calibration_alpha: float,
) -> tuple[np.ndarray, np.ndarray]:
    """Fit the frozen LambdaMART configuration and a train-only score calibrator."""
    scaler = canonical.fit_scaler(dataset, train_qids, "graph")
    matrix = canonical.matrix(dataset, scaler, "graph")
    model = canonical.fit_lambdamart(
        dataset,
        matrix,
        train_qids,
        settings,
        seed,
    )
    scores = np.asarray(
        canonical.predict_model("lambdamart", model, matrix),
        dtype=np.float64,
    )
    train_indices = np.asarray(
        [
            index
            for query_id in sorted(train_qids)
            for index in dataset.by_query[query_id]
        ],
        dtype=int,
    )
    calibrator = Ridge(alpha=calibration_alpha)
    calibrator.fit(
        scores[train_indices].reshape(-1, 1),
        dataset.utility[train_indices],
    )
    predicted_utility = np.clip(
        calibrator.predict(scores.reshape(-1, 1)),
        1.0,
        7.0,
    )
    return scores, predicted_utility


def _baseline_context_for_fold(
    dataset: MixedDataset,
    *,
    fold_row: dict,
    settings: dict,
    original_rankings: dict[tuple[int, int, str, str], dict],
    baseline_arm: str,
    full_arm: str,
    top_k: int,
    inner_folds: int,
    calibration_alpha: float,
) -> tuple[dict[str, dict], list[dict], list[dict]]:
    """Generate outer OOF validation and inner OOF training baseline features."""
    qids = set(dataset.by_query)
    train_qids = sorted(set(map(str, fold_row["train_query_ids"])) & qids)
    valid_qids = sorted(set(map(str, fold_row["validation_query_ids"])) & qids)
    repeat = int(fold_row["repeat"])
    fold = int(fold_row["fold"])
    seed = int(fold_row["seed"])

    outer_scores, outer_predicted = _fit_baseline_scores(
        dataset,
        train_qids,
        settings,
        seed=seed + 2000,
        calibration_alpha=calibration_alpha,
    )
    inner_splits = canonical.inner_folds(
        train_qids,
        inner_folds,
        seed + 7000,
    )
    score_by_query: dict[str, np.ndarray] = {}
    predicted_by_query: dict[str, np.ndarray] = {}
    inner_rows = []
    for inner_index, (inner_train, inner_valid) in enumerate(inner_splits):
        inner_scores, inner_predicted = _fit_baseline_scores(
            dataset,
            inner_train,
            settings,
            seed=seed + 7000 + inner_index,
            calibration_alpha=calibration_alpha,
        )
        for query_id in inner_valid:
            score_by_query[query_id] = inner_scores
            predicted_by_query[query_id] = inner_predicted
        inner_rows.append({
            "inner_fold": inner_index,
            "train_query_ids": inner_train,
            "validation_query_ids": inner_valid,
            "query_overlap": len(set(inner_train) & set(inner_valid)),
        })
    if set(score_by_query) != set(train_qids):
        raise ValueError("inner OOF baseline predictions do not cover outer-train")
    for query_id in valid_qids:
        score_by_query[query_id] = outer_scores
        predicted_by_query[query_id] = outer_predicted

    contexts = {}
    baseline_rows = []
    for query_id in train_qids + valid_qids:
        scores = score_by_query[query_id]
        predicted = predicted_by_query[query_id]
        refit_indices = _rank_depth(dataset, query_id, scores, top_k)
        refit_ids = [
            str(dataset.rows[index]["comment_id"]) for index in refit_indices
        ]
        selected_indices = refit_indices
        selected_ids = refit_ids
        role = "outer_train_inner_oof" if query_id in train_qids else "outer_validation_oof"
        original_baseline = None
        original_full = None
        if query_id in valid_qids:
            key = (repeat, fold, query_id, baseline_arm)
            full_key = (repeat, fold, query_id, full_arm)
            if key not in original_rankings or full_key not in original_rankings:
                raise ValueError(f"missing original OOF comparator for {key}")
            original_baseline = original_rankings[key]
            original_full = original_rankings[full_key]
            frozen_ids = list(map(str, original_baseline["ranked_comment_ids"]))
            # S0 is the immutable historical OOF output.  The current refit is
            # used only for fold-local score features; it must never replace S0.
            selected_ids = frozen_ids
            selected_indices = [
                next(
                    index
                    for index in dataset.by_query[query_id]
                    if str(dataset.rows[index]["comment_id"]) == candidate_id
                )
                for candidate_id in selected_ids
            ]
        score_map = {
            str(dataset.rows[index]["comment_id"]): float(scores[index])
            for index in dataset.by_query[query_id]
        }
        predicted_map = {
            str(dataset.rows[index]["comment_id"]): float(predicted[index])
            for index in dataset.by_query[query_id]
        }
        contexts[query_id] = {
            "role": role,
            "selected_indices": selected_indices,
            "selected_ids": selected_ids,
            "score_by_candidate": score_map,
            "predicted_utility_by_candidate": predicted_map,
            "current_full_ids": (
                list(map(str, original_full["ranked_comment_ids"]))
                if original_full is not None else None
            ),
            "current_full_utility": (
                float(original_full["mean_utility_at8"])
                if original_full is not None else None
            ),
        }
        baseline_rows.append({
            "repeat": repeat,
            "fold": fold,
            "query_id": query_id,
            "role": role,
            "baseline_arm": baseline_arm,
            "baseline_comment_ids": selected_ids,
            "baseline_selector_scores": [score_map[cid] for cid in selected_ids],
            "baseline_predicted_utilities": [
                predicted_map[cid] for cid in selected_ids
            ],
            "reported_outer_oof_exact_match": (
                True if query_id in valid_qids else None
            ),
            "current_refit_exact_match": (
                refit_ids == selected_ids if query_id in valid_qids else None
            ),
            "current_refit_top8_set_overlap": (
                len(set(refit_ids) & set(selected_ids)) / top_k
                if query_id in valid_qids else None
            ),
            "prediction_is_in_sample_for_query": False,
        })
    return contexts, baseline_rows, inner_rows


def _embedding_context(
    *,
    corpus_path: Path,
    corpus_embeddings_path: Path,
    queries_path: Path,
    query_embeddings_path: Path,
    qids: set[str],
    candidate_ids: set[str],
    dense_run_path: Path,
) -> tuple[
    dict[str, np.ndarray],
    dict[str, dict[str, float]],
    dict,
]:
    corpus_rows = json.loads(corpus_path.read_text(encoding="utf-8"))
    corpus_ids = [str(row["title"]) for row in corpus_rows]
    corpus_index = {candidate_id: index for index, candidate_id in enumerate(corpus_ids)}
    if len(corpus_index) != len(corpus_ids):
        raise ValueError("corpus contains duplicate candidate IDs")
    if not candidate_ids <= set(corpus_index):
        raise ValueError("policy candidate IDs are absent from the frozen corpus")
    corpus_embeddings = np.load(corpus_embeddings_path, mmap_mode="r")
    if corpus_embeddings.shape[0] != len(corpus_ids):
        raise ValueError("corpus embedding order cannot be verified")

    query_rows = json.loads(queries_path.read_text(encoding="utf-8"))
    query_ids = sorted(str(row["id"]) for row in query_rows)
    query_index = {query_id: index for index, query_id in enumerate(query_ids)}
    query_embeddings = np.load(query_embeddings_path, mmap_mode="r")
    if query_embeddings.shape[0] != len(query_ids):
        raise ValueError("query embedding order cannot be verified")
    if not qids <= set(query_index):
        raise ValueError("policy query IDs are absent from frozen query embeddings")

    dense_rows = {
        str(row["query_id"]): row
        for row in _read_jsonl(dense_run_path)
        if str(row["query_id"]) in qids
    }
    if set(dense_rows) != qids:
        raise ValueError("dense run does not cover policy queries")
    dense_mismatches = []
    dense_top8_mismatches = []
    dense_top100_overlaps = []
    max_norm_error = 0.0
    for query_id in sorted(qids):
        query_vector = np.asarray(
            query_embeddings[query_index[query_id]],
            dtype=np.float32,
        )
        similarities = np.asarray(corpus_embeddings @ query_vector, dtype=np.float32)
        order = np.argsort(-similarities, kind="stable")[:100]
        replayed = [corpus_ids[int(index)] for index in order]
        reported = list(map(str, dense_rows[query_id]["retrieved_titles"][:100]))
        if replayed != reported:
            dense_mismatches.append(query_id)
        if replayed[:8] != reported[:8]:
            dense_top8_mismatches.append(query_id)
        dense_top100_overlaps.append(
            len(set(replayed) & set(reported)) / 100.0
        )
        max_norm_error = max(
            max_norm_error,
            abs(float(np.linalg.norm(query_vector)) - 1.0),
        )
    reproduction_gate = (
        not dense_top8_mismatches
        and statistics.fmean(dense_top100_overlaps) >= 0.999
        and min(dense_top100_overlaps) >= 0.99
    )
    if not reproduction_gate:
        raise ValueError(
            "frozen SBERT operational reproduction gate failed: "
            f"top8 mismatches={len(dense_top8_mismatches)}, "
            f"mean Top100 overlap={statistics.fmean(dense_top100_overlaps):.6f}, "
            f"minimum={min(dense_top100_overlaps):.6f}"
        )

    candidate_vectors = {
        candidate_id: np.asarray(
            corpus_embeddings[corpus_index[candidate_id]],
            dtype=np.float32,
        )
        for candidate_id in candidate_ids
    }
    score_context: dict[str, dict[str, float]] = {}
    for query_id in sorted(qids):
        query_vector = np.asarray(
            query_embeddings[query_index[query_id]],
            dtype=np.float32,
        )
        scores = {
            candidate_id: _cosine(query_vector, candidate_vectors[candidate_id])
            for candidate_id in candidate_ids
        }
        score_context[query_id] = scores
    return (
        candidate_vectors,
        score_context,
        {
            "dense_top100_replay_mismatch_queries": len(dense_mismatches),
            "dense_top100_exact_queries": len(qids) - len(dense_mismatches),
            "dense_top8_exact_queries": len(qids) - len(dense_top8_mismatches),
            "mean_dense_top100_set_overlap": statistics.fmean(
                dense_top100_overlaps
            ),
            "minimum_dense_top100_set_overlap": min(dense_top100_overlaps),
            "operational_reproduction_gate_passed": reproduction_gate,
            "query_embedding_max_unit_norm_error": max_norm_error,
            "corpus_rows": len(corpus_ids),
            "embedding_dimension": int(corpus_embeddings.shape[1]),
        },
    )


def _pairwise_set_similarity(vectors: list[np.ndarray]) -> tuple[float, float]:
    values = [
        _cosine(vectors[left], vectors[right])
        for left in range(len(vectors))
        for right in range(left + 1, len(vectors))
    ]
    if not values:
        return 0.0, 0.0
    return statistics.fmean(values), max(values)


def _build_action_rows(
    *,
    dataset: MixedDataset,
    query_id: str,
    context: dict,
    candidate_vectors: dict[str, np.ndarray],
    query_scores: dict[str, float],
    provenance_by_pair: dict[tuple[str, str], dict],
    strict_ids: set[str],
    qrels: dict[tuple[str, str], dict],
    repeat: int,
    fold: int,
    allowed_ranks: dict[str, set[int]],
) -> tuple[list[dict], dict]:
    """Freeze utility-blind features first, then attach exact action rewards."""
    selected_ids = list(context["selected_ids"])
    if len(selected_ids) != 8 or len(set(selected_ids)) != 8:
        raise ValueError(f"{query_id}: baseline is not eight unique candidates")
    selected_vectors = [candidate_vectors[candidate_id] for candidate_id in selected_ids]
    tail_vectors = selected_vectors[5:8]
    internal_mean, internal_max = _pairwise_set_similarity(selected_vectors)
    centroid = np.mean(np.asarray(selected_vectors), axis=0)
    centroid_norm = float(np.linalg.norm(centroid))
    if centroid_norm:
        centroid = centroid / centroid_norm

    baseline_scores = context["score_by_candidate"]
    predicted = context["predicted_utility_by_candidate"]
    selected_predicted = [predicted[candidate_id] for candidate_id in selected_ids]
    selected_score_tail = [baseline_scores[candidate_id] for candidate_id in selected_ids[5:8]]
    all_query_candidate_ids = [
        str(dataset.rows[index]["comment_id"])
        for index in dataset.by_query[query_id]
    ]
    all_query_scores = [query_scores[candidate_id] for candidate_id in all_query_candidate_ids]
    relative_values = _minmax(all_query_scores)
    relative_score = dict(zip(all_query_candidate_ids, relative_values, strict=True))
    pool_dispersion = float(np.std(all_query_scores))
    baseline_utility = _utility_at8(selected_ids, query_id, qrels)

    depth_ids = {
        str(dataset.rows[index]["comment_id"])
        for index in dataset.by_query[query_id]
        if str(dataset.rows[index]["candidate_source"]) != GRAPH
    }
    rescue_pools = {
        POOL_STRICT: sorted(strict_ids),
        POOL_FACT_ONLY: sorted(
            candidate_id
            for candidate_id in strict_ids
            if _route_category(provenance_by_pair[(query_id, candidate_id)])
            in {"both_routes", "fact_only_only"}
        ),
        POOL_DEPTH: sorted(depth_ids - set(selected_ids)),
    }
    if len(rescue_pools[POOL_STRICT]) > 4:
        raise ValueError(f"{query_id}: strict Graph pool exceeds four candidates")
    if len(rescue_pools[POOL_DEPTH]) != 4:
        raise ValueError(f"{query_id}: expected exactly four matched Depth rescues")

    rows = []
    pool_summary = {}
    for pool_name, candidate_ids in rescue_pools.items():
        noop = {
            "repeat": repeat,
            "fold": fold,
            "query_id": query_id,
            "role": context["role"],
            "pool": pool_name,
            "action_id": "NOOP",
            "action_type": "NOOP",
            "candidate_id": None,
            "replaced_candidate_id": None,
            "replacement_rank": None,
            "eligible_all8": True,
            "eligible_tail3": True,
            "result_comment_ids": selected_ids,
            "model_features": {name: 0.0 for name in MODEL_FEATURES},
            "diagnostic_features": {},
            "raw_reward_for_training_and_evaluation_only": 0.0,
            "baseline_utility_for_reward_only": baseline_utility,
            "action_utility_for_reward_only": baseline_utility,
            "feature_construction_used_gold_utility": False,
            "eligibility_used_gold_utility": False,
            "inference_used_gold_utility": False,
            "fallback_used": False,
            "callback_used": False,
            "padding_used": False,
            "route_membership": "NOOP",
        }
        rows.append(noop)
        positive_actions = 0
        for candidate_id in candidate_ids:
            if candidate_id in selected_ids:
                raise ValueError(f"{query_id}: rescue candidate already in baseline")
            candidate_index = next(
                index
                for index in dataset.by_query[query_id]
                if str(dataset.rows[index]["comment_id"]) == candidate_id
            )
            candidate_row = dataset.rows[candidate_index]
            provenance = provenance_by_pair[(query_id, candidate_id)]
            route_category = _route_category(provenance)
            graph_ranks = {
                str(route): int(rank)
                for route, rank in provenance.get("graph_pre_fallback_rank", {}).items()
            }
            graph_scores = {
                str(route): float(score)
                for route, score in provenance.get("native_graph_score", {}).items()
            }
            no_rank = graph_ranks.get("no_recognition")
            fact_rank = graph_ranks.get("fact_only_no_recognition")
            no_score = graph_scores.get("no_recognition", 0.0)
            fact_score = graph_scores.get("fact_only_no_recognition", 0.0)
            no_rank_norm = 1.0 - (no_rank - 1) / 99.0 if no_rank is not None else 0.0
            fact_rank_norm = (
                1.0 - (fact_rank - 1) / 99.0 if fact_rank is not None else 0.0
            )
            route_features = dict(candidate_row.get("route_features") or {})
            no_norm_score = float(route_features.get("no_recognition_score", 0.0))
            fact_norm_score = float(
                route_features.get("fact_only_no_recognition_score", 0.0)
            )
            rank_agreement = (
                1.0 - abs(no_rank - fact_rank) / 99.0
                if no_rank is not None and fact_rank is not None else 0.0
            )
            score_agreement = (
                1.0 - abs(no_norm_score - fact_norm_score)
                if no_rank is not None and fact_rank is not None else 0.0
            )

            candidate_vector = candidate_vectors[candidate_id]
            similarities = [
                _cosine(candidate_vector, selected_vector)
                for selected_vector in selected_vectors
            ]
            candidate_max_similarity = max(similarities)
            candidate_mean_similarity = statistics.fmean(similarities)
            candidate_novelty = 1.0 - candidate_max_similarity
            tail_similarity = max(
                _cosine(candidate_vector, tail_vector)
                for tail_vector in tail_vectors
            )
            centroid_distance = 1.0 - _cosine(candidate_vector, centroid)
            source_rank = int(candidate_row["source_rank"])
            candidate_predicted = predicted[candidate_id]
            candidate_selector_score = baseline_scores[candidate_id]
            candidate_relevance = query_scores[candidate_id]

            for replacement_rank, replaced_id in enumerate(selected_ids, start=1):
                replaced_vector = candidate_vectors[replaced_id]
                other_vectors = [
                    vector
                    for index, vector in enumerate(selected_vectors, start=1)
                    if index != replacement_rank
                ]
                replaced_max_other = max(
                    _cosine(replaced_vector, other)
                    for other in other_vectors
                )
                replaced_novelty = 1.0 - replaced_max_other
                features = {
                    "sbert_query_candidate_score": candidate_relevance,
                    "sbert_query_candidate_relative": relative_score[candidate_id],
                    "ppr_no_recognition_score": no_score,
                    "ppr_no_recognition_rank_norm": no_rank_norm,
                    "ppr_fact_only_score": fact_score,
                    "ppr_fact_only_rank_norm": fact_rank_norm,
                    "route_both": float(route_category == "both_routes"),
                    "route_fact_only_only": float(
                        route_category == "fact_only_only"
                    ),
                    "route_no_recognition_only": float(
                        route_category == "no_recognition_only"
                    ),
                    "route_rank_agreement": rank_agreement,
                    "route_score_agreement": score_agreement,
                    "graph_exclusive": float(
                        provenance["graph_exclusive_relative_to_D8_Depth4"]
                    ),
                    "dense_score_missing": float(not provenance["native_dense"]),
                    "candidate_novelty_to_s0": candidate_novelty,
                    "candidate_mean_similarity_to_s0": candidate_mean_similarity,
                    "candidate_tail_similarity": tail_similarity,
                    "candidate_centroid_distance": centroid_distance,
                    "s0_internal_mean_similarity": internal_mean,
                    "predicted_utility_difference": (
                        candidate_predicted - predicted[replaced_id]
                    ),
                    "query_relevance_difference": (
                        candidate_relevance - query_scores[replaced_id]
                    ),
                    "baseline_selector_score_difference": (
                        candidate_selector_score - baseline_scores[replaced_id]
                    ),
                    "novelty_difference": candidate_novelty - replaced_novelty,
                    "candidate_replaced_similarity": _cosine(
                        candidate_vector,
                        replaced_vector,
                    ),
                    "normalized_rank_difference": (
                        source_rank - replacement_rank
                    ) / 8.0,
                    "s0_predicted_utility_std": float(
                        np.std(selected_predicted)
                    ),
                }
                if tuple(features) != MODEL_FEATURES:
                    raise AssertionError("model feature order drifted")
                if any(
                    forbidden in feature_name
                    for feature_name in features
                    for forbidden in FORBIDDEN_INFERENCE_FEATURES
                ):
                    raise AssertionError("forbidden inference feature present")
                diagnostics = {
                    "candidate_max_similarity_to_s0": candidate_max_similarity,
                    "s0_internal_max_similarity": internal_max,
                    "s0_predicted_utility_min": min(selected_predicted),
                    "s0_predicted_utility_mean": statistics.fmean(
                        selected_predicted
                    ),
                    "s0_predicted_utility_max": max(selected_predicted),
                    "s0_tail_selector_score_gap": (
                        max(selected_score_tail) - min(selected_score_tail)
                    ),
                    "candidate_pool_sbert_score_dispersion": pool_dispersion,
                }
                result_ids = list(selected_ids)
                result_ids[replacement_rank - 1] = candidate_id
                action_utility = _utility_at8(result_ids, query_id, qrels)
                reward = action_utility - baseline_utility
                positive_actions += reward > 0
                rows.append({
                    "repeat": repeat,
                    "fold": fold,
                    "query_id": query_id,
                    "role": context["role"],
                    "pool": pool_name,
                    "action_id": (
                        f"replace:r{replacement_rank}:{candidate_id}"
                    ),
                    "action_type": "REPLACE",
                    "candidate_id": candidate_id,
                    "replaced_candidate_id": replaced_id,
                    "replacement_rank": replacement_rank,
                    "candidate_source_rank": source_rank,
                    "eligible_all8": replacement_rank in allowed_ranks["all8"],
                    "eligible_tail3": replacement_rank in allowed_ranks["tail3"],
                    "result_comment_ids": result_ids,
                    "model_features": features,
                    "diagnostic_features": diagnostics,
                    "raw_reward_for_training_and_evaluation_only": reward,
                    "baseline_utility_for_reward_only": baseline_utility,
                    "action_utility_for_reward_only": action_utility,
                    "feature_construction_used_gold_utility": False,
                    "eligibility_used_gold_utility": False,
                    "inference_used_gold_utility": False,
                    "fallback_used": bool(provenance["fallback_used"]),
                    "callback_used": bool(provenance["callback_used"]),
                    "padding_used": bool(provenance["padding_used"]),
                    "native_graph": bool(provenance["native_graph"]),
                    "graph_exclusive_relative_to_D8_Depth4": bool(
                        provenance[
                            "graph_exclusive_relative_to_D8_Depth4"
                        ]
                    ),
                    "route_membership": route_category,
                    "fact_only_supported": route_category
                    in {"both_routes", "fact_only_only"},
                    "source_attribution_traceable": bool(
                        provenance["source_attribution_traceable"]
                    ),
                })
        pool_summary[pool_name] = {
            "candidate_count": len(candidate_ids),
            "action_count_all8": 1 + len(candidate_ids) * 8,
            "action_count_tail3": 1 + len(candidate_ids) * 3,
            "positive_action_count_all8": positive_actions,
        }
    return rows, pool_summary


def _eligible_rows(
    rows: list[dict],
    *,
    pool: str,
    action_space: str,
    qids: set[str] | None = None,
) -> list[dict]:
    eligibility_key = f"eligible_{action_space}"
    return [
        row
        for row in rows
        if row["pool"] == pool
        and bool(row[eligibility_key])
        and (qids is None or str(row["query_id"]) in qids)
    ]


def _feature_matrix(
    rows: list[dict],
    feature_names: tuple[str, ...] = MODEL_FEATURES,
) -> np.ndarray:
    return np.asarray(
        [
            [float(row["model_features"][name]) for name in feature_names]
            for row in rows
        ],
        dtype=np.float64,
    )


@dataclass
class _ModelBundle:
    family: str
    scaler: StandardScaler
    model: object
    feature_names: tuple[str, ...] = MODEL_FEATURES


class _LinearPolicy(nn.Module):
    def __init__(self, input_dim: int) -> None:
        super().__init__()
        self.linear = nn.Linear(input_dim, 1, bias=False)
        nn.init.zeros_(self.linear.weight)

    def forward(self, values: torch.Tensor) -> torch.Tensor:
        return self.linear(values).squeeze(-1)


class _SmallMLPPolicy(nn.Module):
    def __init__(self, input_dim: int, hidden_size: int, dropout: float) -> None:
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(input_dim, hidden_size),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(hidden_size, 1),
        )

    def forward(self, values: torch.Tensor) -> torch.Tensor:
        return self.network(values).squeeze(-1)


def _query_weighted_training_rows(
    rows: list[dict],
    qids: list[str],
) -> tuple[list[dict], np.ndarray]:
    by_query = defaultdict(list)
    for row in rows:
        if row["action_type"] == "REPLACE" and str(row["query_id"]) in qids:
            by_query[str(row["query_id"])].append(row)
    selected = [row for query_id in qids for row in by_query[query_id]]
    weights = np.asarray(
        [
            1.0 / max(1, len(by_query[str(row["query_id"])]))
            for row in selected
        ],
        dtype=np.float64,
    )
    return selected, weights


def _downside_weight(reward: float, kappa: float) -> float:
    return reward if reward >= 0 else kappa * reward


def _policy_training_tensor(
    rows: list[dict],
    qids: list[str],
    scaler: StandardScaler,
    kappa: float,
    feature_names: tuple[str, ...] = MODEL_FEATURES,
) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
    by_query = defaultdict(list)
    for row in rows:
        if row["action_type"] == "REPLACE" and str(row["query_id"]) in qids:
            by_query[str(row["query_id"])].append(row)
    max_actions = max((len(by_query[query_id]) for query_id in qids), default=0)
    if max_actions == 0:
        raise ValueError("policy training has no intervention actions")
    features = np.zeros(
        (len(qids), max_actions + 1, len(feature_names)),
        dtype=np.float32,
    )
    rewards = np.zeros((len(qids), max_actions + 1), dtype=np.float32)
    mask = np.zeros((len(qids), max_actions + 1), dtype=bool)
    mask[:, 0] = True
    for query_index, query_id in enumerate(qids):
        action_rows = sorted(
            by_query[query_id],
            key=lambda row: str(row["action_id"]),
        )
        if not action_rows:
            continue
        transformed = scaler.transform(
            _feature_matrix(action_rows, feature_names)
        ).astype(np.float32)
        count = len(action_rows)
        features[query_index, 1 : count + 1] = transformed
        rewards[query_index, 1 : count + 1] = [
            _downside_weight(
                float(row["raw_reward_for_training_and_evaluation_only"]),
                kappa,
            )
            for row in action_rows
        ]
        mask[query_index, 1 : count + 1] = True
    return (
        torch.tensor(features),
        torch.tensor(rewards),
        torch.tensor(mask),
    )


def _fit_action_model(
    rows: list[dict],
    train_qids: list[str],
    *,
    family: str,
    kappa: float,
    config: dict,
    seed: int,
    feature_names: tuple[str, ...] = MODEL_FEATURES,
) -> _ModelBundle:
    intervention_rows, weights = _query_weighted_training_rows(rows, train_qids)
    if not intervention_rows:
        raise ValueError("no eligible interventions in policy training fold")
    scaler = StandardScaler().fit(
        _feature_matrix(intervention_rows, feature_names)
    )
    transformed = scaler.transform(
        _feature_matrix(intervention_rows, feature_names)
    )
    targets = np.asarray(
        [
            _downside_weight(
                float(row["raw_reward_for_training_and_evaluation_only"]),
                kappa,
            )
            for row in intervention_rows
        ],
        dtype=np.float64,
    )
    if family == "direct_delta":
        model = HuberRegressor(
            epsilon=float(config["huber_epsilon"]),
            alpha=float(config["l2_alpha"]),
            max_iter=int(config["max_iter"]),
            fit_intercept=True,
        )
        model.fit(transformed, targets, sample_weight=weights)
        return _ModelBundle(
            family=family,
            scaler=scaler,
            model=model,
            feature_names=feature_names,
        )

    torch.manual_seed(seed)
    np.random.seed(seed)
    if family == "linear_policy":
        model = _LinearPolicy(len(feature_names))
    elif family == "small_mlp_policy":
        model = _SmallMLPPolicy(
            len(feature_names),
            int(config["hidden_size"]),
            float(config["dropout"]),
        )
    else:
        raise ValueError(f"unknown model family: {family}")
    optimizer = torch.optim.Adam(
        model.parameters(),
        lr=float(config["learning_rate"]),
    )
    feature_tensor, reward_tensor, mask_tensor = _policy_training_tensor(
        rows,
        train_qids,
        scaler,
        kappa,
        feature_names,
    )
    epochs = int(config["epochs"])
    l2 = float(config["l2"])
    for _ in range(epochs):
        model.train()
        optimizer.zero_grad()
        scores = model(feature_tensor)
        scores = scores.clone()
        scores[:, 0] = 0.0
        scores = scores.masked_fill(~mask_tensor, -1e9)
        probabilities = torch.softmax(scores, dim=1)
        expected = (probabilities * reward_tensor).sum(dim=1).mean()
        penalty = sum(
            parameter.square().sum() for parameter in model.parameters()
        )
        loss = -expected + l2 * penalty
        loss.backward()
        optimizer.step()
    return _ModelBundle(
        family=family,
        scaler=scaler,
        model=model,
        feature_names=feature_names,
    )


def _predict_action_scores(
    bundle: _ModelBundle,
    rows: list[dict],
) -> dict[str, float]:
    interventions = [row for row in rows if row["action_type"] == "REPLACE"]
    result = {"NOOP": 0.0}
    if not interventions:
        return result
    transformed = bundle.scaler.transform(
        _feature_matrix(interventions, bundle.feature_names)
    )
    if bundle.family == "direct_delta":
        scores = bundle.model.predict(transformed)
    else:
        bundle.model.eval()
        with torch.no_grad():
            scores = bundle.model(
                torch.tensor(transformed, dtype=torch.float32)
            ).numpy()
    for row, score in zip(interventions, scores, strict=True):
        result[str(row["action_id"])] = float(score)
    return result


def _best_decision(
    rows: list[dict],
    scores: dict[str, float],
    *,
    threshold: float,
) -> dict:
    interventions = [row for row in rows if row["action_type"] == "REPLACE"]
    noop = next(row for row in rows if row["action_type"] == "NOOP")
    if not interventions:
        return {
            "selected": noop,
            "acted": False,
            "predicted_margin": None,
            "best_intervention_reward": None,
            "best_intervention_action_id": None,
        }
    best = max(
        interventions,
        key=lambda row: (
            scores[str(row["action_id"])],
            str(row["action_id"]),
        ),
    )
    margin = float(scores[str(best["action_id"])])
    acted = margin > threshold
    return {
        "selected": best if acted else noop,
        "acted": acted,
        "predicted_margin": margin,
        "best_intervention_reward": (
            float(best["raw_reward_for_training_and_evaluation_only"])
            if best.get("raw_reward_for_training_and_evaluation_only") is not None
            else None
        ),
        "best_intervention_action_id": str(best["action_id"]),
    }


def _threshold_candidates(
    margins: list[float],
    quantiles: list[float],
) -> list[float]:
    positive = np.asarray(
        [margin for margin in margins if math.isfinite(margin) and margin > 0],
        dtype=np.float64,
    )
    values = {0.0}
    if positive.size:
        values.update(
            float(np.quantile(positive, quantile))
            for quantile in quantiles
        )
    return sorted(values)


def _threshold_metrics(decisions: list[dict], threshold: float) -> dict:
    rewards = [
        float(row["best_intervention_reward"])
        if row["predicted_margin"] is not None
        and float(row["predicted_margin"]) > threshold
        else 0.0
        for row in decisions
    ]
    acted = [
        row["predicted_margin"] is not None
        and float(row["predicted_margin"]) > threshold
        for row in decisions
    ]
    mean_reward, standard_error = _mean_and_se(rewards)
    action_count = sum(acted)
    harmful = sum(
        action and reward < 0 for action, reward in zip(acted, rewards, strict=True)
    )
    return {
        "threshold": threshold,
        "queries": len(rewards),
        "mean_raw_reward": mean_reward,
        "standard_error": standard_error,
        "conservative_objective": mean_reward - 0.5 * standard_error,
        "action_rate": action_count / len(rewards) if rewards else 0.0,
        "harmful_action_rate_all_queries": (
            harmful / len(rewards) if rewards else 0.0
        ),
    }


def _tune_action_model(
    rows: list[dict],
    train_qids: list[str],
    inner_splits: list[tuple[list[str], list[str]]],
    *,
    family: str,
    model_config: dict,
    kappa_options: list[float],
    threshold_quantiles: list[float],
    seed: int,
    feature_names: tuple[str, ...] = MODEL_FEATURES,
) -> tuple[dict, list[dict]]:
    traces = []
    for kappa_index, kappa in enumerate(kappa_options):
        decisions = []
        for inner_index, (inner_train, inner_valid) in enumerate(inner_splits):
            bundle = _fit_action_model(
                rows,
                inner_train,
                family=family,
                kappa=float(kappa),
                config=model_config,
                seed=seed + kappa_index * 101 + inner_index,
                feature_names=feature_names,
            )
            for query_id in inner_valid:
                query_rows = [
                    row for row in rows if str(row["query_id"]) == query_id
                ]
                scores = _predict_action_scores(bundle, query_rows)
                decision = _best_decision(
                    query_rows,
                    scores,
                    threshold=-math.inf,
                )
                decisions.append({
                    "query_id": query_id,
                    "predicted_margin": decision["predicted_margin"],
                    "best_intervention_reward": (
                        decision["best_intervention_reward"]
                    ),
                })
        if {row["query_id"] for row in decisions} != set(train_qids):
            raise ValueError("inner policy OOF predictions do not cover train queries")
        thresholds = _threshold_candidates(
            [
                float(row["predicted_margin"])
                for row in decisions
                if row["predicted_margin"] is not None
            ],
            threshold_quantiles,
        )
        threshold_rows = [
            _threshold_metrics(decisions, threshold)
            for threshold in thresholds
        ]
        best_threshold = max(
            threshold_rows,
            key=lambda row: (
                row["conservative_objective"],
                row["mean_raw_reward"],
                -row["harmful_action_rate_all_queries"],
                -row["action_rate"],
                row["threshold"],
            ),
        )
        traces.append({
            "kappa": float(kappa),
            "inner_oof_queries": len(decisions),
            "thresholds": threshold_rows,
            "selected_threshold_for_kappa": best_threshold,
        })
    best = max(
        traces,
        key=lambda row: (
            row["selected_threshold_for_kappa"]["conservative_objective"],
            row["selected_threshold_for_kappa"]["mean_raw_reward"],
            -row["selected_threshold_for_kappa"][
                "harmful_action_rate_all_queries"
            ],
            -row["selected_threshold_for_kappa"]["action_rate"],
            row["selected_threshold_for_kappa"]["threshold"],
            -row["kappa"],
        ),
    )
    return {
        "kappa": float(best["kappa"]),
        "threshold": float(
            best["selected_threshold_for_kappa"]["threshold"]
        ),
        "inner_conservative_objective": float(
            best["selected_threshold_for_kappa"]["conservative_objective"]
        ),
    }, traces


def _oracle_reward(rows: list[dict]) -> float:
    return max(
        float(row["raw_reward_for_training_and_evaluation_only"])
        for row in rows
    )


def _evaluate_fold_variant(
    action_rows: list[dict],
    *,
    pool: str,
    action_space: str,
    family: str,
    train_qids: list[str],
    valid_qids: list[str],
    inner_splits: list[tuple[list[str], list[str]]],
    model_config: dict,
    kappa_options: list[float],
    threshold_quantiles: list[float],
    seed: int,
    baseline_contexts: dict[str, dict],
    feature_names: tuple[str, ...] = MODEL_FEATURES,
) -> tuple[list[dict], dict]:
    eligible = _eligible_rows(
        action_rows,
        pool=pool,
        action_space=action_space,
        qids=set(train_qids) | set(valid_qids),
    )
    selected_config, tuning_trace = _tune_action_model(
        eligible,
        train_qids,
        inner_splits,
        family=family,
        model_config=model_config,
        kappa_options=kappa_options,
        threshold_quantiles=threshold_quantiles,
        seed=seed,
        feature_names=feature_names,
    )
    bundle = _fit_action_model(
        eligible,
        train_qids,
        family=family,
        kappa=selected_config["kappa"],
        config=model_config,
        seed=seed + 90000,
        feature_names=feature_names,
    )
    predictions = []
    for query_id in valid_qids:
        query_rows = [
            row for row in eligible if str(row["query_id"]) == query_id
        ]
        scores = _predict_action_scores(bundle, query_rows)
        oracle = _oracle_reward(query_rows)
        context = baseline_contexts[query_id]
        for threshold_mode, threshold in (
            ("none", 0.0),
            ("nested", selected_config["threshold"]),
        ):
            decision = _best_decision(
                query_rows,
                scores,
                threshold=threshold,
            )
            selected = decision["selected"]
            reward = float(
                selected["raw_reward_for_training_and_evaluation_only"]
            )
            baseline_utility = float(
                selected["baseline_utility_for_reward_only"]
            )
            predictions.append({
                "repeat": int(selected["repeat"]),
                "fold": int(selected["fold"]),
                "query_id": query_id,
                "arm": (
                    f"{pool}__{action_space}__{family}__{threshold_mode}"
                ),
                "pool": pool,
                "action_space": action_space,
                "model_family": family,
                "threshold_mode": threshold_mode,
                "selected_kappa": selected_config["kappa"],
                "selected_threshold": threshold,
                "acted": bool(decision["acted"]),
                "selected_action_id": str(selected["action_id"]),
                "selected_candidate_id": selected["candidate_id"],
                "replaced_candidate_id": selected["replaced_candidate_id"],
                "replacement_rank": selected["replacement_rank"],
                "route_membership": selected["route_membership"],
                "predicted_margin": decision["predicted_margin"],
                "best_intervention_action_id": decision[
                    "best_intervention_action_id"
                ],
                "best_intervention_reward": decision[
                    "best_intervention_reward"
                ],
                "raw_reward": reward,
                "baseline_utility_at8": baseline_utility,
                "policy_utility_at8": baseline_utility + reward,
                "current_full_utility_at8": context["current_full_utility"],
                "action_space_oracle_headroom": oracle,
                "successful_action": bool(decision["acted"] and reward > 0),
                "harmful_action": bool(decision["acted"] and reward < 0),
                "fallback_used": bool(selected["fallback_used"]),
                "callback_used": bool(selected["callback_used"]),
                "padding_used": bool(selected["padding_used"]),
                "source_attribution_traceable": bool(
                    selected.get("source_attribution_traceable", True)
                ),
                "inference_used_gold_utility": False,
            })
    return predictions, {
        "pool": pool,
        "action_space": action_space,
        "model_family": family,
        "model_config": model_config,
        "feature_names": list(feature_names),
        "selected": selected_config,
        "tuning_trace": tuning_trace,
    }


def _query_aggregate(
    rows: list[dict],
    field: str,
) -> dict[str, float]:
    grouped = defaultdict(list)
    for row in rows:
        grouped[str(row["query_id"])].append(float(row[field]))
    return {
        query_id: statistics.fmean(values)
        for query_id, values in grouped.items()
    }


def _aggregate_policy_arm(
    rows: list[dict],
    *,
    bootstrap_samples: int,
    bootstrap_seed: int,
) -> dict:
    arm = str(rows[0]["arm"])
    delta_by_query = _query_aggregate(rows, "raw_reward")
    oracle_by_query = _query_aggregate(rows, "action_space_oracle_headroom")
    baseline_by_query = _query_aggregate(rows, "baseline_utility_at8")
    policy_by_query = _query_aggregate(rows, "policy_utility_at8")
    full_by_query = _query_aggregate(rows, "current_full_utility_at8")
    query_ids = sorted(delta_by_query)
    deltas = [delta_by_query[query_id] for query_id in query_ids]
    lo, hi = bootstrap_ci(
        deltas,
        n_boot=bootstrap_samples,
        seed=bootstrap_seed + len(arm),
    )

    acted_by_query = defaultdict(list)
    success_by_query = defaultdict(list)
    harm_by_query = defaultdict(list)
    positive_rewards = defaultdict(list)
    negative_rewards = defaultdict(list)
    route_counts = Counter()
    for row in rows:
        query_id = str(row["query_id"])
        acted_by_query[query_id].append(float(row["acted"]))
        success_by_query[query_id].append(float(row["successful_action"]))
        harm_by_query[query_id].append(float(row["harmful_action"]))
        if row["successful_action"]:
            positive_rewards[query_id].append(float(row["raw_reward"]))
        if row["harmful_action"]:
            negative_rewards[query_id].append(float(row["raw_reward"]))
        if row["acted"]:
            route_counts[str(row["route_membership"])] += 1

    action_mass = sum(
        statistics.fmean(acted_by_query[query_id]) for query_id in query_ids
    )
    success_mass = sum(
        statistics.fmean(success_by_query[query_id]) for query_id in query_ids
    )
    harm_mass = sum(
        statistics.fmean(harm_by_query[query_id]) for query_id in query_ids
    )
    opportunities = [
        query_id for query_id in query_ids if oracle_by_query[query_id] > 0
    ]
    captured_mass = sum(
        statistics.fmean(success_by_query[query_id])
        for query_id in opportunities
    )
    positive_conditional = [
        statistics.fmean(values) for values in positive_rewards.values()
    ]
    negative_conditional = [
        statistics.fmean(values) for values in negative_rewards.values()
    ]
    oracle_mean = statistics.fmean(oracle_by_query.values())
    delta_mean = statistics.fmean(deltas)
    return {
        "arm": arm,
        "pool": rows[0]["pool"],
        "action_space": rows[0]["action_space"],
        "model_family": rows[0]["model_family"],
        "threshold_mode": rows[0]["threshold_mode"],
        "oof_rows": len(rows),
        "unique_queries": len(query_ids),
        "repeats_per_query": sorted(
            {len(acted_by_query[query_id]) for query_id in query_ids}
        ),
        "mean_raw_utility_at8_delta": delta_mean,
        "query_bootstrap_95ci": [lo, hi],
        "mean_baseline_utility_at8": statistics.fmean(
            baseline_by_query.values()
        ),
        "mean_policy_utility_at8": statistics.fmean(policy_by_query.values()),
        "mean_current_full_utility_at8": statistics.fmean(
            full_by_query.values()
        ),
        "action_rate": action_mass / len(query_ids),
        "noop_rate": 1.0 - action_mass / len(query_ids),
        "successful_action_rate_all_queries": success_mass / len(query_ids),
        "harmful_action_rate_all_queries": harm_mass / len(query_ids),
        "successful_action_rate_conditional_on_action": (
            success_mass / action_mass if action_mass else None
        ),
        "harmful_action_rate_conditional_on_action": (
            harm_mass / action_mass if action_mass else None
        ),
        "mean_gain_conditional_on_successful_action": (
            statistics.fmean(positive_conditional)
            if positive_conditional else None
        ),
        "mean_loss_conditional_on_harmful_action": (
            statistics.fmean(negative_conditional)
            if negative_conditional else None
        ),
        "entrant_precision": (
            success_mass / action_mass if action_mass else None
        ),
        "opportunity_queries": len(opportunities),
        "opportunity_recall": (
            captured_mass / len(opportunities) if opportunities else None
        ),
        "distinct_queries_acted": sum(
            any(value > 0 for value in acted_by_query[query_id])
            for query_id in query_ids
        ),
        "action_space_oracle_headroom": oracle_mean,
        "oracle_conversion_ratio": (
            delta_mean / oracle_mean if oracle_mean else None
        ),
        "regret_to_action_space_oracle": oracle_mean - delta_mean,
        "actions_by_route_membership_across_repeat_rows": dict(
            sorted(route_counts.items())
        ),
        "fallback_callback_padding_entrants": sum(
            bool(row["acted"])
            and (
                bool(row["fallback_used"])
                or bool(row["callback_used"])
                or bool(row["padding_used"])
            )
            for row in rows
        ),
    }


def _paired_contrast(
    left_rows: list[dict],
    right_rows: list[dict] | None,
    *,
    right_name: str,
    bootstrap_samples: int,
    bootstrap_seed: int,
) -> dict:
    left = _query_aggregate(left_rows, "raw_reward")
    if right_rows is None:
        right = {query_id: 0.0 for query_id in left}
    else:
        right = _query_aggregate(right_rows, "raw_reward")
    query_ids = sorted(set(left) & set(right))
    deltas = [left[query_id] - right[query_id] for query_id in query_ids]
    lo, hi = bootstrap_ci(
        deltas,
        n_boot=bootstrap_samples,
        seed=bootstrap_seed + len(left_rows[0]["arm"]) + len(right_name),
    )
    return {
        "left": left_rows[0]["arm"],
        "right": right_name,
        "queries": len(query_ids),
        "mean_delta": statistics.fmean(deltas),
        "query_bootstrap_95ci": [lo, hi],
        "improved_tied_degraded": [
            sum(value > 1e-12 for value in deltas),
            sum(abs(value) <= 1e-12 for value in deltas),
            sum(value < -1e-12 for value in deltas),
        ],
    }


def _full_comparator_contrast(
    rows: list[dict],
    *,
    full_arm: str,
    bootstrap_samples: int,
    bootstrap_seed: int,
) -> dict:
    grouped = defaultdict(list)
    for row in rows:
        grouped[str(row["query_id"])].append(
            float(row["policy_utility_at8"])
            - float(row["current_full_utility_at8"])
        )
    deltas = [statistics.fmean(values) for values in grouped.values()]
    lo, hi = bootstrap_ci(
        deltas,
        n_boot=bootstrap_samples,
        seed=bootstrap_seed + len(rows[0]["arm"]) + len(full_arm),
    )
    return {
        "left": rows[0]["arm"],
        "right": full_arm,
        "queries": len(deltas),
        "mean_delta": statistics.fmean(deltas),
        "query_bootstrap_95ci": [lo, hi],
        "improved_tied_degraded": [
            sum(value > 1e-12 for value in deltas),
            sum(abs(value) <= 1e-12 for value in deltas),
            sum(value < -1e-12 for value in deltas),
        ],
    }


def _oracle_summary(
    action_rows: list[dict],
    *,
    pool: str,
    action_space: str,
    validation_only: bool = True,
    route_filter: str | None = None,
) -> dict:
    rows = _eligible_rows(
        action_rows,
        pool=pool,
        action_space=action_space,
    )
    if validation_only:
        rows = [row for row in rows if row["role"] == "outer_validation_oof"]
    grouped = defaultdict(list)
    for row in rows:
        if (
            route_filter is not None
            and row["action_type"] == "REPLACE"
            and row["route_membership"] != route_filter
        ):
            continue
        grouped[
            (int(row["repeat"]), int(row["fold"]), str(row["query_id"]))
        ].append(row)
    rewards_by_query = defaultdict(list)
    for (_, _, query_id), query_rows in grouped.items():
        noop = [row for row in query_rows if row["action_type"] == "NOOP"]
        if not noop:
            # Route-filtered diagnostic still needs its explicit zero action.
            query_rows = [
                {
                    "raw_reward_for_training_and_evaluation_only": 0.0,
                    "action_type": "NOOP",
                },
                *query_rows,
            ]
        rewards_by_query[query_id].append(_oracle_reward(query_rows))
    aggregated = {
        query_id: statistics.fmean(values)
        for query_id, values in rewards_by_query.items()
    }
    return {
        "pool": pool if route_filter is None else POOL_NO_RECOGNITION_ONLY,
        "action_space": action_space,
        "queries": len(aggregated),
        "mean_oracle_headroom": statistics.fmean(aggregated.values()),
        "opportunity_queries": sum(value > 0 for value in aggregated.values()),
        "per_query": aggregated,
    }


def _risk_coverage_rows(rows: list[dict]) -> list[dict]:
    grouped = defaultdict(list)
    for row in rows:
        grouped[str(row["query_id"])].append(row)
    summaries = []
    for query_id, query_rows in grouped.items():
        finite = [
            row for row in query_rows
            if row["predicted_margin"] is not None
        ]
        summaries.append({
            "query_id": query_id,
            "mean_margin": (
                statistics.fmean(float(row["predicted_margin"]) for row in finite)
                if finite else -math.inf
            ),
            "mean_best_reward": (
                statistics.fmean(
                    float(row["best_intervention_reward"]) for row in finite
                )
                if finite else 0.0
            ),
        })
    ordered = sorted(
        summaries,
        key=lambda row: (-row["mean_margin"], row["query_id"]),
    )
    output = []
    for coverage in [index / 10.0 for index in range(11)]:
        count = int(round(coverage * len(ordered)))
        selected = ordered[:count]
        selected_ids = {row["query_id"] for row in selected}
        rewards = [
            row["mean_best_reward"] if row["query_id"] in selected_ids else 0.0
            for row in ordered
        ]
        output.append({
            "arm": rows[0]["arm"],
            "pool": rows[0]["pool"],
            "action_space": rows[0]["action_space"],
            "model_family": rows[0]["model_family"],
            "coverage_target": coverage,
            "acted_queries": count,
            "actual_action_rate": count / len(ordered),
            "mean_raw_utility_at8_delta": statistics.fmean(rewards),
            "harmful_action_rate_conditional_on_action": (
                sum(row["mean_best_reward"] < 0 for row in selected) / count
                if count else None
            ),
            "successful_action_rate_conditional_on_action": (
                sum(row["mean_best_reward"] > 0 for row in selected) / count
                if count else None
            ),
        })
    return output


def _per_query_rows(oof_rows: list[dict]) -> list[dict]:
    grouped = defaultdict(list)
    for row in oof_rows:
        grouped[(str(row["query_id"]), str(row["arm"]))].append(row)
    output = []
    for (query_id, arm), rows in sorted(grouped.items()):
        output.append({
            "query_id": query_id,
            "arm": arm,
            "pool": rows[0]["pool"],
            "action_space": rows[0]["action_space"],
            "model_family": rows[0]["model_family"],
            "threshold_mode": rows[0]["threshold_mode"],
            "repeat_rows": len(rows),
            "mean_raw_utility_at8_delta": statistics.fmean(
                float(row["raw_reward"]) for row in rows
            ),
            "mean_baseline_utility_at8": statistics.fmean(
                float(row["baseline_utility_at8"]) for row in rows
            ),
            "mean_policy_utility_at8": statistics.fmean(
                float(row["policy_utility_at8"]) for row in rows
            ),
            "mean_action_space_oracle_headroom": statistics.fmean(
                float(row["action_space_oracle_headroom"]) for row in rows
            ),
            "action_rate": statistics.fmean(float(row["acted"]) for row in rows),
            "successful_action_rate": statistics.fmean(
                float(row["successful_action"]) for row in rows
            ),
            "harmful_action_rate": statistics.fmean(
                float(row["harmful_action"]) for row in rows
            ),
            "mean_predicted_margin": statistics.fmean(
                float(row["predicted_margin"])
                for row in rows
                if row["predicted_margin"] is not None
            ) if any(
                row["predicted_margin"] is not None for row in rows
            ) else None,
            "fallback_callback_padding_entrant": any(
                bool(row["acted"])
                and (
                    bool(row["fallback_used"])
                    or bool(row["callback_used"])
                    or bool(row["padding_used"])
                )
                for row in rows
            ),
        })
    return output


def _resolve_config(
    config_key: str,
) -> tuple[Path, dict, dict, dict[str, Path]]:
    root = Path(__file__).resolve().parents[1]
    all_config = project_config.load()
    policy = dict(all_config[config_key])
    source = dict(all_config[str(policy["source_experiment_key"])])
    paths = {
        "output_dir": _resolve(root, policy["output_dir"]),
        "provenance_audit_dir": _resolve(root, policy["provenance_audit_dir"]),
        "dense_reproduction_audit": _resolve(
            root,
            policy["dense_reproduction_audit"],
        ),
        "corpus": _resolve(root, policy["corpus"]),
        "corpus_embeddings": _resolve(root, policy["corpus_embeddings"]),
        "queries": _resolve(root, policy["queries"]),
        "query_embeddings": _resolve(root, policy["query_embeddings"]),
        "candidate_pool": _resolve(root, source["candidate_pool"]),
        "utility_registry": _resolve(root, source["utility_registry"]),
        "dense_run": _resolve(root, source["dense_run"]),
        "split_manifest": _resolve(root, source["split_manifest"]),
        "source_output_dir": _resolve(root, source["output_dir"]),
    }
    for path in paths.values():
        _reject_test(path)
    return root, policy, source, paths


def _determine_verdict(
    aggregate: dict[str, dict],
) -> tuple[str, dict]:
    confirmatory_families = ("direct_delta", "linear_policy")
    comparisons = []
    for family in confirmatory_families:
        graph_arm = (
            f"{POOL_STRICT}__all8__{family}__nested"
        )
        depth_arm = (
            f"{POOL_DEPTH}__all8__{family}__nested"
        )
        graph = aggregate[graph_arm]
        depth = aggregate[depth_arm]
        comparisons.append({
            "family": family,
            "graph_arm": graph_arm,
            "depth_arm": depth_arm,
            "graph_delta": graph["mean_raw_utility_at8_delta"],
            "graph_ci": graph["query_bootstrap_95ci"],
            "depth_delta": depth["mean_raw_utility_at8_delta"],
            "graph_minus_depth": (
                graph["mean_raw_utility_at8_delta"]
                - depth["mean_raw_utility_at8_delta"]
            ),
            "graph_distinct_queries_acted": graph[
                "distinct_queries_acted"
            ],
            "provenance_violations": graph[
                "fallback_callback_padding_entrants"
            ],
        })
    positive = [row for row in comparisons if row["graph_delta"] > 0]
    graph_specific = [
        row for row in positive if row["graph_minus_depth"] > 0
    ]
    if positive and not graph_specific:
        verdict = "SECOND_STAGE_REPLACEMENT_EFFECT_NOT_GRAPH_SPECIFIC"
    elif any(
        row["graph_ci"][0] > 0
        and row["provenance_violations"] == 0
        for row in graph_specific
    ):
        verdict = "STRICT_NATIVE_GRAPH_HEADROOM_CONVERTED"
    elif any(
        row["graph_distinct_queries_acted"] >= 10
        and row["provenance_violations"] == 0
        for row in graph_specific
    ):
        verdict = "STRICT_NATIVE_GRAPH_SELECTIVE_SIGNAL_ONLY"
    else:
        verdict = (
            "STRICT_NATIVE_GRAPH_NOT_CONVERTED_BY_CONSERVATIVE_ONE_STEP_POLICY"
        )
    if verdict not in VERDICTS:
        raise AssertionError(verdict)
    return verdict, {"confirmatory_family_comparisons": comparisons}


def run(
    config_key: str = "strict_native_graph_conservative_policy",
) -> dict:
    root, policy, source, paths = _resolve_config(config_key)
    out_dir = paths["output_dir"]
    if out_dir.exists():
        raise FileExistsError(f"refusing to overwrite versioned output: {out_dir}")
    required_paths = [
        paths["candidate_pool"],
        paths["utility_registry"],
        paths["dense_run"],
        paths["split_manifest"],
        paths["dense_reproduction_audit"],
        paths["corpus"],
        paths["corpus_embeddings"],
        paths["queries"],
        paths["query_embeddings"],
        paths["provenance_audit_dir"] / "candidate_provenance.jsonl",
        paths["provenance_audit_dir"] / "strict_native_graph_pool.jsonl",
        paths["provenance_audit_dir"] / "strict_native_graph_audit_report.json",
        paths["source_output_dir"] / "mixed_candidate_feature_registry.jsonl",
        paths["source_output_dir"] / "oof_rankings.jsonl",
        paths["source_output_dir"] / "nested_fold_audit.json",
        paths["source_output_dir"] / "strict_sbert_mixed_selector_report.json",
    ]
    for path in required_paths:
        _reject_test(path)
        if not path.exists():
            raise FileNotFoundError(path)

    source_report_path = (
        paths["source_output_dir"] / "strict_sbert_mixed_selector_report.json"
    )
    source_report = json.loads(source_report_path.read_text(encoding="utf-8"))
    dense_reproduction_audit = json.loads(
        paths["dense_reproduction_audit"].read_text(encoding="utf-8")
    )
    if not bool(dense_reproduction_audit.get("gate_passed")):
        raise ValueError("source strict-SBERT dense reproduction gate did not pass")
    baseline_arm = str(policy["baseline_arm"])
    full_arm = str(policy["full_comparator_arm"])
    if baseline_arm != "mixed_lambdamart_depth":
        raise ValueError("baseline must remain the pre-reported best Depth-only arm")
    if full_arm != "mixed_lambdamart_full":
        raise ValueError("Full comparator must remain the matched pre-reported arm")
    depth_arms = {
        arm: values["mean_utility_at8"]["mean"]
        for arm, values in source_report["arms"].items()
        if arm.endswith("_depth")
    }
    if max(depth_arms, key=depth_arms.get) != baseline_arm:
        raise ValueError("configured baseline is not the pre-reported best Depth arm")

    feature_rows = _read_jsonl(
        paths["source_output_dir"] / "mixed_candidate_feature_registry.jsonl"
    )
    pool_rows = _read_jsonl(paths["candidate_pool"])
    if {
        (str(row["query_id"]), str(row["comment_id"])) for row in feature_rows
    } != {
        (str(row["query_id"]), str(row["comment_id"])) for row in pool_rows
    }:
        raise ValueError("feature registry and frozen candidate pool differ")
    complete_rows, complete_registry = complete_utility_v2_rows(
        _read_jsonl(paths["utility_registry"])
    )
    qrels = {
        (str(query_id), str(candidate_id)): row
        for (query_id, candidate_id), row in complete_registry.items()
    }
    qrels_float = {
        key: float(row["utility"]) for key, row in qrels.items()
    }
    dataset = MixedDataset(feature_rows, qrels_float)
    qids = set(dataset.by_query)
    if len(qids) != 100 or len(feature_rows) != 1600:
        raise ValueError("strict policy expects the frozen 100×16 pool")

    provenance_rows = _read_jsonl(
        paths["provenance_audit_dir"] / "candidate_provenance.jsonl"
    )
    provenance_by_pair = {
        (str(row["query_id"]), str(row["candidate_id"])): row
        for row in provenance_rows
    }
    strict_rows = _read_jsonl(
        paths["provenance_audit_dir"] / "strict_native_graph_pool.jsonl"
    )
    strict_by_query: dict[str, set[str]] = defaultdict(set)
    for row in strict_rows:
        strict_by_query[str(row["query_id"])].add(str(row["candidate_id"]))
    if sum(map(len, strict_by_query.values())) != 400:
        raise ValueError("strict-native Graph pool changed")
    if any(
        bool(row["fallback_used"])
        or bool(row["callback_used"])
        or bool(row["padding_used"])
        or not bool(row["native_graph"])
        or not bool(row["graph_exclusive_relative_to_D8_Depth4"])
        for row in strict_rows
    ):
        raise ValueError("strict-native provenance contract failed")

    original_rankings_rows = _read_jsonl(
        paths["source_output_dir"] / "oof_rankings.jsonl"
    )
    original_rankings = {
        (
            int(row["repeat"]),
            int(row["fold"]),
            str(row["query_id"]),
            str(row["arm"]),
        ): row
        for row in original_rankings_rows
    }
    fold_audit = json.loads(
        (
            paths["source_output_dir"] / "nested_fold_audit.json"
        ).read_text(encoding="utf-8")
    )
    baseline_settings = {
        (int(row["repeat"]), int(row["fold"])): row[
            "mixed_lambdamart_config"
        ]
        for row in fold_audit["folds"]
    }
    split_source = json.loads(paths["split_manifest"].read_text(encoding="utf-8"))
    split_rows = sorted(
        split_source["rows"],
        key=lambda row: (int(row["repeat"]), int(row["fold"])),
    )
    if len(split_rows) != 25 or set(baseline_settings) != {
        (int(row["repeat"]), int(row["fold"])) for row in split_rows
    }:
        raise ValueError("outer split or frozen baseline settings changed")

    candidate_ids = {
        str(row["comment_id"]) for row in feature_rows
    }
    (
        candidate_vectors,
        query_score_context,
        embedding_audit,
    ) = _embedding_context(
        corpus_path=paths["corpus"],
        corpus_embeddings_path=paths["corpus_embeddings"],
        queries_path=paths["queries"],
        query_embeddings_path=paths["query_embeddings"],
        qids=qids,
        candidate_ids=candidate_ids,
        dense_run_path=paths["dense_run"],
    )
    query_score_context = {
        query_id: {
            candidate_id: query_score_context[query_id][candidate_id]
            for candidate_id in candidate_ids
            if (query_id, candidate_id) in provenance_by_pair
        }
        for query_id in qids
    }

    action_spaces = {
        name: set(map(int, ranks))
        for name, ranks in policy["action_spaces"].items()
    }
    if action_spaces != {
        "all8": set(range(1, 9)),
        "tail3": {6, 7, 8},
    }:
        raise ValueError("action-space contract changed")
    torch.set_num_threads(1)

    all_action_rows = []
    all_baseline_rows = []
    oof_rows = []
    fold_metrics = []
    split_output_rows = []
    action_pool_summaries = []
    validation_counts: Counter[tuple[int, str]] = Counter()
    for outer_index, fold_row in enumerate(split_rows):
        repeat = int(fold_row["repeat"])
        fold = int(fold_row["fold"])
        seed = int(fold_row["seed"])
        train_qids = sorted(set(map(str, fold_row["train_query_ids"])) & qids)
        valid_qids = sorted(set(map(str, fold_row["validation_query_ids"])) & qids)
        if set(train_qids) & set(valid_qids):
            raise ValueError("query overlap in outer split")
        if set(train_qids) | set(valid_qids) != qids:
            raise ValueError("filtered outer split does not partition strict pool")
        for query_id in valid_qids:
            validation_counts[(repeat, query_id)] += 1

        contexts, baseline_rows, baseline_inner_rows = (
            _baseline_context_for_fold(
                dataset,
                fold_row=fold_row,
                settings=baseline_settings[(repeat, fold)],
                original_rankings=original_rankings,
                baseline_arm=baseline_arm,
                full_arm=full_arm,
                top_k=int(policy["top_k"]),
                inner_folds=int(policy["inner_folds"]),
                calibration_alpha=float(
                    policy["baseline_calibration_alpha"]
                ),
            )
        )
        fold_actions = []
        for query_id in train_qids + valid_qids:
            query_actions, pool_summary = _build_action_rows(
                dataset=dataset,
                query_id=query_id,
                context=contexts[query_id],
                candidate_vectors=candidate_vectors,
                query_scores=query_score_context[query_id],
                provenance_by_pair=provenance_by_pair,
                strict_ids=strict_by_query[query_id],
                qrels=qrels,
                repeat=repeat,
                fold=fold,
                allowed_ranks=action_spaces,
            )
            fold_actions.extend(query_actions)
            action_pool_summaries.append({
                "repeat": repeat,
                "fold": fold,
                "query_id": query_id,
                "role": contexts[query_id]["role"],
                **pool_summary,
            })
        all_action_rows.extend(fold_actions)
        all_baseline_rows.extend(baseline_rows)

        inner_splits = [
            (
                list(map(str, row["train_query_ids"])),
                list(map(str, row["validation_query_ids"])),
            )
            for row in baseline_inner_rows
        ]
        policy_fold_rows = []
        policy_fold_audits = []
        model_configs = {
            "direct_delta": dict(policy["direct_delta"]),
            "linear_policy": dict(policy["linear_policy"]),
            "small_mlp_policy": dict(policy["small_mlp_policy"]),
        }
        for pool in (POOL_STRICT, POOL_FACT_ONLY, POOL_DEPTH):
            for action_space in ("all8", "tail3"):
                for family in MODEL_FAMILIES:
                    predictions, audit = _evaluate_fold_variant(
                        fold_actions,
                        pool=pool,
                        action_space=action_space,
                        family=family,
                        train_qids=train_qids,
                        valid_qids=valid_qids,
                        inner_splits=inner_splits,
                        model_config=model_configs[family],
                        kappa_options=list(map(float, policy["kappa_options"])),
                        threshold_quantiles=list(
                            map(float, policy["threshold_quantiles"])
                        ),
                        seed=seed
                        + 100000 * outer_index
                        + 100 * ("all8", "tail3").index(action_space)
                        + 10 * MODEL_FAMILIES.index(family),
                        baseline_contexts=contexts,
                    )
                    policy_fold_rows.extend(predictions)
                    policy_fold_audits.append(audit)
        oof_rows.extend(policy_fold_rows)
        fold_metrics.append({
            "repeat": repeat,
            "fold": fold,
            "seed": seed,
            "outer_train_queries": len(train_qids),
            "outer_validation_queries": len(valid_qids),
            "frozen_baseline_config": baseline_settings[(repeat, fold)],
            "baseline_inner_splits": baseline_inner_rows,
            "policy_variants": policy_fold_audits,
        })
        split_output_rows.append({
            "repeat": repeat,
            "fold": fold,
            "seed": seed,
            "train_query_ids": train_qids,
            "validation_query_ids": valid_qids,
        })
        print(json.dumps({
            "repeat": repeat,
            "fold": fold,
            "validation_queries": len(valid_qids),
            "policy_rows": len(policy_fold_rows),
            "status": "COMPLETE",
        }, sort_keys=True), flush=True)

    repeats = sorted({int(row["repeat"]) for row in split_rows})
    if any(
        validation_counts[(repeat, query_id)] != 1
        for repeat in repeats
        for query_id in qids
    ):
        raise ValueError("each query must be validation exactly once per repeat")
    expected_oof = (
        len(qids)
        * len(repeats)
        * 3
        * 2
        * len(MODEL_FAMILIES)
        * len(THRESHOLD_MODES)
    )
    if len(oof_rows) != expected_oof:
        raise ValueError(f"OOF row count {len(oof_rows)} != {expected_oof}")

    arms = sorted({str(row["arm"]) for row in oof_rows})
    aggregate = {
        arm: _aggregate_policy_arm(
            [row for row in oof_rows if str(row["arm"]) == arm],
            bootstrap_samples=int(policy["bootstrap_samples"]),
            bootstrap_seed=int(policy["bootstrap_seed"]),
        )
        for arm in arms
    }
    oracle_summaries = {}
    for pool in (POOL_STRICT, POOL_FACT_ONLY, POOL_DEPTH):
        for action_space in ("all8", "tail3"):
            oracle_summaries[f"{pool}__{action_space}"] = _oracle_summary(
                all_action_rows,
                pool=pool,
                action_space=action_space,
            )
    no_recognition_oracles = {
        action_space: _oracle_summary(
            all_action_rows,
            pool=POOL_STRICT,
            action_space=action_space,
            route_filter="no_recognition_only",
        )
        for action_space in ("all8", "tail3")
    }
    strict_all = oracle_summaries[f"{POOL_STRICT}__all8"]
    strict_tail = oracle_summaries[f"{POOL_STRICT}__tail3"]
    depth_all = oracle_summaries[f"{POOL_DEPTH}__all8"]
    action_space_oracle = {
        "graph_all8": {
            key: value for key, value in strict_all.items() if key != "per_query"
        },
        "graph_tail3": {
            key: value for key, value in strict_tail.items() if key != "per_query"
        },
        "tail3_coverage_of_all8": (
            strict_tail["mean_oracle_headroom"]
            / strict_all["mean_oracle_headroom"]
            if strict_all["mean_oracle_headroom"] else None
        ),
        "depth_rescue_all8": {
            key: value for key, value in depth_all.items() if key != "per_query"
        },
        "fact_only_supported_all8": {
            key: value
            for key, value in oracle_summaries[
                f"{POOL_FACT_ONLY}__all8"
            ].items()
            if key != "per_query"
        },
        "no_recognition_only": {
            action_space: {
                key: value for key, value in summary.items() if key != "per_query"
            }
            for action_space, summary in no_recognition_oracles.items()
        },
        "candidate_pool_oracle_reference": 0.17393749999999997,
        "candidate_pool_oracle_is_not_conversion_denominator": True,
    }

    by_arm_rows = {
        arm: [row for row in oof_rows if str(row["arm"]) == arm]
        for arm in arms
    }
    contrasts = []
    for family in MODEL_FAMILIES:
        for threshold_mode in THRESHOLD_MODES:
            graph_arm = (
                f"{POOL_STRICT}__all8__{family}__{threshold_mode}"
            )
            depth_arm = (
                f"{POOL_DEPTH}__all8__{family}__{threshold_mode}"
            )
            contrasts.append(_paired_contrast(
                by_arm_rows[graph_arm],
                None,
                right_name=baseline_arm,
                bootstrap_samples=int(policy["bootstrap_samples"]),
                bootstrap_seed=int(policy["bootstrap_seed"]),
            ))
            contrasts.append(_paired_contrast(
                by_arm_rows[depth_arm],
                None,
                right_name=baseline_arm,
                bootstrap_samples=int(policy["bootstrap_samples"]),
                bootstrap_seed=int(policy["bootstrap_seed"]),
            ))
            contrasts.append(_paired_contrast(
                by_arm_rows[graph_arm],
                by_arm_rows[depth_arm],
                right_name=depth_arm,
                bootstrap_samples=int(policy["bootstrap_samples"]),
                bootstrap_seed=int(policy["bootstrap_seed"]),
            ))
            contrasts.append(_full_comparator_contrast(
                by_arm_rows[graph_arm],
                full_arm=full_arm,
                bootstrap_samples=int(policy["bootstrap_samples"]),
                bootstrap_seed=int(policy["bootstrap_seed"]),
            ))

    risk_rows = []
    for arm in arms:
        if arm.endswith("__none"):
            risk_rows.extend(_risk_coverage_rows(by_arm_rows[arm]))
    per_query_rows = _per_query_rows(oof_rows)
    verdict, verdict_diagnostic = _determine_verdict(aggregate)

    strict_graph_action_rows = [
        row
        for row in all_action_rows
        if row["pool"] in {POOL_STRICT, POOL_FACT_ONLY}
        and row["action_type"] == "REPLACE"
    ]
    graph_entrant_rows = [
        row
        for row in oof_rows
        if row["pool"] in {POOL_STRICT, POOL_FACT_ONLY}
        and row["acted"]
    ]
    assertions = {
        "frozen_depth_baseline_arm_unchanged": (
            baseline_arm == "mixed_lambdamart_depth"
        ),
        "outer_validation_baseline_exact_replay_rows": sum(
            row["role"] == "outer_validation_oof"
            and row["reported_outer_oof_exact_match"] is True
            for row in all_baseline_rows
        ),
        "outer_train_baseline_predictions_all_inner_oof": all(
            not bool(row["prediction_is_in_sample_for_query"])
            for row in all_baseline_rows
        ),
        "strict_graph_action_fallback_used_zero": sum(
            bool(row["fallback_used"]) for row in strict_graph_action_rows
        ),
        "strict_graph_action_callback_used_zero": sum(
            bool(row["callback_used"]) for row in strict_graph_action_rows
        ),
        "strict_graph_action_padding_used_zero": sum(
            bool(row["padding_used"]) for row in strict_graph_action_rows
        ),
        "strict_graph_entrants_all_traceable": all(
            bool(row["source_attribution_traceable"])
            for row in graph_entrant_rows
        ),
        "strict_graph_entrant_fallback_callback_padding_zero": sum(
            bool(row["fallback_used"])
            or bool(row["callback_used"])
            or bool(row["padding_used"])
            for row in graph_entrant_rows
        ),
        "model_feature_count": len(MODEL_FEATURES),
        "forbidden_inference_features_present": False,
        "query_grouped_outer_split_unchanged": True,
        "matched_graph_depth_model_seed_identical": True,
        "repeat_rows_aggregated_before_bootstrap": True,
        "test_read": False,
        "external_model_calls": 0,
        "gold_utility_used_as_inference_feature": False,
        "original_outputs_overwritten": False,
    }
    if (
        assertions["outer_validation_baseline_exact_replay_rows"] != 500
        or assertions["strict_graph_action_fallback_used_zero"] != 0
        or assertions["strict_graph_action_callback_used_zero"] != 0
        or assertions["strict_graph_action_padding_used_zero"] != 0
        or not assertions["strict_graph_entrants_all_traceable"]
        or assertions[
            "strict_graph_entrant_fallback_callback_padding_zero"
        ] != 0
        or assertions["model_feature_count"] > 25
    ):
        raise AssertionError(assertions)

    fact_only_signal = aggregate[
        f"{POOL_FACT_ONLY}__all8__direct_delta__nested"
    ]["mean_raw_utility_at8_delta"]
    strict_signal = aggregate[
        f"{POOL_STRICT}__all8__direct_delta__nested"
    ]["mean_raw_utility_at8_delta"]
    provenance_sensitivity_wording = (
        "PPR candidates with Dense passage-restart support showed the signal"
        if strict_signal > 0 and fact_only_signal <= 0
        else (
            "The fact-only-supported sensitivity retained the direction of "
            "the strict-native-all result."
        )
    )

    input_paths = {
        "candidate_pool": paths["candidate_pool"],
        "utility_registry": paths["utility_registry"],
        "dense_run": paths["dense_run"],
        "dense_reproduction_audit": paths["dense_reproduction_audit"],
        "split_manifest": paths["split_manifest"],
        "corpus": paths["corpus"],
        "corpus_embeddings": paths["corpus_embeddings"],
        "queries": paths["queries"],
        "query_embeddings": paths["query_embeddings"],
        "candidate_provenance": (
            paths["provenance_audit_dir"] / "candidate_provenance.jsonl"
        ),
        "strict_native_graph_pool": (
            paths["provenance_audit_dir"] / "strict_native_graph_pool.jsonl"
        ),
        "source_report": source_report_path,
        "source_oof_rankings": (
            paths["source_output_dir"] / "oof_rankings.jsonl"
        ),
        "source_nested_fold_audit": (
            paths["source_output_dir"] / "nested_fold_audit.json"
        ),
        "source_feature_registry": (
            paths["source_output_dir"]
            / "mixed_candidate_feature_registry.jsonl"
        ),
    }
    inputs = {
        name: {"path": str(path.resolve()), "sha256": _sha256(path)}
        for name, path in input_paths.items()
    }
    report = {
        "schema": "strict-native-graph-conservative-policy-v1",
        "version": str(policy["version"]),
        "created_at": datetime.now(timezone.utc).isoformat(),
        "scope": (
            "development-only LLM-silver full-information one-step contextual "
            "policy learning; no frozen test and no external calls"
        ),
        "verdict": verdict,
        "research_question": (
            "Can a NO-OP-aware one-swap policy directly trained on replacement "
            "utility convert strict native Graph candidate headroom into OOF "
            "Utility@8 gain?"
        ),
        "frozen_baseline": {
            "arm": baseline_arm,
            "pre_reported_mean_utility_at8": source_report["arms"][
                baseline_arm
            ]["mean_utility_at8"]["mean"],
            "pre_reported_query_bootstrap_95ci": source_report["arms"][
                baseline_arm
            ]["mean_utility_at8"]["query_bootstrap_95ci"],
            "selection_rule": (
                "highest pre-reported Depth-only Utility@8 arm in docs_v2/87; "
                "fixed before the new policy ran"
            ),
            "family": str(policy["baseline_family"]),
            "feature_set": str(policy["baseline_feature_set"]),
            "outer_validation_exact_replay_rows": 500,
            "current_environment_refit_exact_rows": sum(
                row["current_refit_exact_match"] is True
                for row in all_baseline_rows
            ),
            "current_environment_refit_mean_top8_set_overlap": (
                statistics.fmean(
                    float(row["current_refit_top8_set_overlap"])
                    for row in all_baseline_rows
                    if row["current_refit_top8_set_overlap"] is not None
                )
            ),
            "outer_train_upstream_predictions": "inner query-grouped OOF",
            "report_sha256": _sha256(source_report_path),
            "oof_rankings_sha256": _sha256(
                paths["source_output_dir"] / "oof_rankings.jsonl"
            ),
            "nested_fold_audit_sha256": _sha256(
                paths["source_output_dir"] / "nested_fold_audit.json"
            ),
        },
        "current_best_full_selector": {
            "arm": full_arm,
            "pre_reported_mean_utility_at8": source_report["arms"][
                full_arm
            ]["mean_utility_at8"]["mean"],
            "matched_full_minus_depth_mean": next(
                row["mean_delta"]
                for row in source_report[
                    "matched_graph_availability_contrasts"
                ]
                if row["left"] == full_arm
                and row["right"] == baseline_arm
                and row["metric"] == "mean_utility_at8"
            ),
        },
        "action_space_oracle": action_space_oracle,
        "arms": aggregate,
        "contrasts": contrasts,
        "verdict_diagnostic": verdict_diagnostic,
        "provenance_sensitivity_wording": provenance_sensitivity_wording,
        "embedding_audit": embedding_audit,
        "assertions": assertions,
        "inputs": inputs,
        "utility_registry_complete_rows": len(complete_rows),
        "method_identity": {
            "name": "full-information one-step contextual policy learning",
            "also_describable_as": (
                "contextual-bandit-style conservative policy"
            ),
            "not": ["PPO", "GRPO", "REINFORCE", "multi-step agent", "logged bandit"],
            "direct_delta": "scikit-learn HuberRegressor with L2 alpha",
            "linear_policy": (
                "own thin full-information softmax objective over all actions"
            ),
            "small_mlp_policy": (
                "exploratory one-hidden-layer full-information softmax policy"
            ),
        },
        "claim_boundary": (
            "All rewards are existing development utility-v2 silver labels. "
            "A positive OOF result is neither frozen-test evidence, human "
            "preference evidence, nor answer-level utility."
        ),
        "recommendation": (
            "Stop increasing selector complexity and do not proceed to PPO, "
            "GRPO, GNN policies, or larger Graph quota."
            if verdict
            == "STRICT_NATIVE_GRAPH_NOT_CONVERTED_BY_CONSERVATIVE_ONE_STEP_POLICY"
            else (
                "Retain only the verdict-strength claim and validate on the "
                "frozen confirmatory protocol before deployment claims."
            )
        ),
    }

    feature_manifest = {
        "schema": "strict-native-graph-conservative-policy-features-v1",
        "model_feature_count": len(MODEL_FEATURES),
        "model_features": list(MODEL_FEATURES),
        "diagnostic_only_features": list(DIAGNOSTIC_FEATURES),
        "forbidden_inference_features": list(FORBIDDEN_INFERENCE_FEATURES),
        "normalization": (
            "StandardScaler fitted separately inside each policy inner/outer "
            "training-query partition; NO-OP score fixed to zero"
        ),
        "baseline_score_and_predicted_utility": (
            "outer-train query features are inner OOF; outer-validation features "
            "are from an outer-train-only refit and Ridge score calibrator. "
            "The immutable S0 IDs are consumed directly from the historical OOF "
            "ranking rather than replaced by the current-environment refit."
        ),
        "candidate_embeddings": {
            "backend": "sentence-transformers/all-MiniLM-L6-v2",
            "corpus_embeddings_sha256": _sha256(paths["corpus_embeddings"]),
            "query_embeddings_sha256": _sha256(paths["query_embeddings"]),
            "dense_operational_reproduction_gate_passed": (
                embedding_audit["operational_reproduction_gate_passed"]
            ),
            "dense_top8_exact_queries": embedding_audit[
                "dense_top8_exact_queries"
            ],
            "dense_top100_exact_queries": embedding_audit[
                "dense_top100_exact_queries"
            ],
            "gate_definition": dense_reproduction_audit["gate_definition"],
        },
        "graph_seed_mass_used": False,
        "gold_utility_used_as_feature": False,
        "reward_attached_after_feature_freeze": True,
    }
    split_manifest = {
        "schema": "strict-native-graph-conservative-policy-splits-v1",
        "unit": "query_id",
        "source": {
            "path": str(paths["split_manifest"].resolve()),
            "sha256": _sha256(paths["split_manifest"]),
        },
        "queries": len(qids),
        "repeats": len(repeats),
        "folds": len(split_rows),
        "rows": split_output_rows,
        "query_overlap_per_outer_fold": 0,
        "validation_appearances_per_query": len(repeats),
        "test_read": False,
    }

    output_names = [
        "action_table.jsonl",
        "baseline_sets.jsonl",
        "oof_actions.jsonl",
        "fold_metrics.json",
        "per_query_metrics.csv",
        "risk_coverage.csv",
        "feature_manifest.json",
        "split_manifest.json",
        "strict_native_graph_conservative_policy_report.json",
    ]
    out_dir.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(
        prefix=f".{out_dir.name}.",
        dir=out_dir.parent,
    ) as temporary:
        temp_dir = Path(temporary)
        _write_jsonl(temp_dir / "action_table.jsonl", all_action_rows)
        _write_jsonl(temp_dir / "baseline_sets.jsonl", all_baseline_rows)
        _write_jsonl(temp_dir / "oof_actions.jsonl", oof_rows)
        _write_json(temp_dir / "fold_metrics.json", {"folds": fold_metrics})
        _write_csv(temp_dir / "per_query_metrics.csv", per_query_rows)
        _write_csv(temp_dir / "risk_coverage.csv", risk_rows)
        _write_json(temp_dir / "feature_manifest.json", feature_manifest)
        _write_json(temp_dir / "split_manifest.json", split_manifest)
        _write_json(
            temp_dir / "strict_native_graph_conservative_policy_report.json",
            report,
        )
        _write_json(temp_dir / "manifest.json", {
            "schema": report["schema"],
            "version": report["version"],
            "status": "COMPLETE",
            "verdict": verdict,
            "queries": len(qids),
            "action_rows": len(all_action_rows),
            "baseline_rows": len(all_baseline_rows),
            "oof_action_rows": len(oof_rows),
            "folds": len(fold_metrics),
            "external_model_calls": 0,
            "test_read": False,
            "original_outputs_overwritten": False,
            "files": {
                name: {"sha256": _sha256(temp_dir / name)}
                for name in output_names
            },
        })
        os.replace(temp_dir, out_dir)
    return report


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--config-key",
        default="strict_native_graph_conservative_policy",
    )
    args = parser.parse_args()
    report = run(args.config_key)
    primary_arms = {
        arm: {
            "delta": values["mean_raw_utility_at8_delta"],
            "ci": values["query_bootstrap_95ci"],
            "action_rate": values["action_rate"],
            "conversion": values["oracle_conversion_ratio"],
        }
        for arm, values in report["arms"].items()
        if values["pool"] in {POOL_STRICT, POOL_DEPTH}
        and values["action_space"] == "all8"
        and values["threshold_mode"] == "nested"
    }
    print(json.dumps({
        "status": "COMPLETE",
        "verdict": report["verdict"],
        "action_space_oracle": report["action_space_oracle"],
        "primary_arms": primary_arms,
        "assertions": report["assertions"],
    }, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
